# Generated by Django 2.1.7 on 2021-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
