# Generated by Django 2.1.7 on 2021-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='itemPic/')),
            ],
        ),
    ]
