# Generated by Django 2.1.7 on 2021-04-29 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0004_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('card', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('ph', models.CharField(max_length=250)),
                ('Add1', models.CharField(max_length=250)),
                ('Add2', models.CharField(max_length=250)),
                ('Add3', models.CharField(max_length=250)),
                ('odate', models.DateField()),
                ('ddate', models.DateField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropapp.crops')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropapp.userregister')),
            ],
        ),
    ]
