# Generated by Django 2.1.7 on 2021-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnum', models.CharField(max_length=60, unique=True)),
                ('cvv', models.CharField(max_length=10)),
                ('bal', models.IntegerField()),
            ],
        ),
    ]
