# Generated by Django 2.1.7 on 2021-04-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0007_soilprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='weatherPrediction',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('ph', models.FloatField()),
                ('rain', models.FloatField()),
                ('result', models.CharField(max_length=40)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropapp.userregister')),
            ],
        ),
    ]
