# Generated by Django 2.1.7 on 2021-05-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0008_weatherprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expdate',
            field=models.DateField(default='1995-01-01'),
            preserve_default=False,
        ),
    ]
