# Generated by Django 2.1.7 on 2021-05-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0009_account_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expdate',
            field=models.DateField(default='1995-01-01'),
        ),
    ]
