# Generated by Django 2.1.7 on 2021-05-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cropapp', '0011_auto_20210517_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('quest', models.TextField()),
                ('rep', models.TextField(default='pending')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropapp.userregister')),
            ],
        ),
    ]
